#
NAME=lapackGRPY_x64
DIR=../../lib/
FC = i686-w64-mingw32-gfortran
FFLAGS = -c -O2 -static

 %.o64 : %.f
	$(FC) $(FFLAGS) $<

OBJECTS = \
lapblas_matInv.o lapack_dgsev.o lapack_dsyev.o

$(NAMEFUL) : $(OBJECTS)
	ar cr $(DIR)lib$(NAME).a $(OBJECTS)

all: $(OBJECTS)
	ar cr $(DIR)lib$(NAME).a $(OBJECTS)

clean:
	rm -f *.o $(DIR)lib$(NAME).a
