cmd.load(filename='1ubq.pdb')
cmd.show(representation="cartoon")
cmd.spectrum()
scale=2.9/1.4
for i in open('1ubqNoHeHR_shell.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=1,name="a"))([float(j) for j in i.split()])
for i in open('1ubq-pri.bea'): (lambda x: cmd.pseudoatom(pos=[x[0]*scale,x[1]*scale,x[2]*scale,0.1],vdw=2.9,b=2,name="dlt"))([float(j) for j in i.split()[3:]])
for i in open('1ubq_1-A20R50hiOT-so.bead_lsit'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=3,name="somo"))([float(j) for j in i.split()[0:4]])
cmd.translate(vector=[34.,0.,0.],selection="name a")
cmd.translate(vector=[68,0.,0.],selection="name somo")
cmd.translate(vector=[104.,0.,0.],selection="name dlt")
cmd.bg_color(color="white")
cmd.color('red',selection='name a')
cmd.color('orange',selection='name somo')
cmd.color('green',selection='name dlt')
cmd.show(representation="sph",selection='name a')
cmd.show(representation="sph",selection='name somo')
cmd.show(representation="sph",selection='name dlt')
cmd.rotate('x',angle=90)
cmd.reset()
cmd.move('z',170)
cmd.set(name="orthoscopic",value="on")
cmd.center()
