#!/bin/bash

#for fold in [1248]* dim[1245]*
#for fold in 1g0b 1ova dim1hco dim2aai raw1a4v
for fold in 1zag
do
    if [ -d "$fold" ]
    then
        cd $fold
        for i in *.bead_model
        do 
            if [ -e $i ]
            then
                j=${i%.bead_model}
                newFile=$j".bod"
                newFile=$(echo "${newFile/A10R30syOThyG2/OThyG2}")
                newFile=$(echo "${newFile/A10R30syOThyG5/OThyG5}")
                newFile=$(echo "${newFile/A20R50hiOT/hiOT}")
                newFile=$(echo "${newFile/A20R50-so_ovlp/ovlp}")
                echo "units A" > $newFile
                echo "temp 20 C" >> $newFile
                echo "solvent water" >> $newFile
                nLines=$(head -n1 $i | cut -f1);
                mw=$(head -n $(($nLines+1)) $i | tail -n $nLines | awk '{s+=$5}END{print s}')
                echo mass $mw Da >> $newFile
                head -n $(($nLines+1)) $i | tail -n $nLines | cut -f1-4 | sed -e 's/^/s /' >> $newFile
            fi
        done 
        cd ..    
    fi
done


