for i in open('1hrc_1-A10R30hyG2-a2b.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=1,name="A2ov"))([float(j) for j in i.split()])
for i in open('1hrc_1-A10R30syOThyG2-a2b.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=2,name="A2"))([float(j) for j in i.split()])
cmd.translate(vector=[0.,-40.,0.],selection="name A2")
for i in open('1hrc_1-A10R30hyG5-a2b.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=1,name="A5ov"))([float(j) for j in i.split()])
cmd.translate(vector=[50,0,0],selection="name A5ov")
for i in open('1hrc_1-A10R30syOThyG5-a2b.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=2,name="A5"))([float(j) for j in i.split()])
cmd.translate(vector=[50,-40,0],selection="name A5")
for i in open('1hrc_1-A20R50-so_ovlp.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=1,name="Soov"))([float(j) for j in i.split()])
cmd.translate(vector=[100,0,0],selection="name Soov")
for i in open('1hrc_1-A20R50hiOT-so.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=2,name="So"))([float(j) for j in i.split()])
cmd.translate(vector=[100,-40,0],selection="name So")
for i in open('1hrc.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=1,name="a"))([float(j) for j in i.split()])
cmd.translate(vector=[-50.,0.,0.],selection="name a")
for i in open('1hrc_shell.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=2,name="sh"))([float(j) for j in i.split()])
cmd.translate(vector=[-50.,-40.,0.],selection="name sh")
cmd.bg_color(color="white")
cmd.show(representation="sph")
cmd.spectrum(expression="b")
cmd.set(name="orthoscopic",value="on")
cmd.center()
