for i in open('1btaNoHeHR_shell.xyzr'): (lambda x: cmd.pseudoatom(pos=x[0:3],vdw=x[3],b=1,name="a"))([float(j) for j in i.split()])
for i in open('1bta-pri.bea'): (lambda x: cmd.pseudoatom(pos=[x[0],x[1],x[2],0.1],vdw=3.0,b=2,name="dlt"))([float(j) for j in i.split()[3:]])
cmd.load(filename='1bta.pdb')
cmd.translate(vector=[-40.,0.,0.],selection="name a")
cmd.translate(vector=[40.,0.,0.],selection="name dlt")
cmd.bg_color(color="white")
cmd.show(representation="sph")
cmd.spectrum(expression="b")
cmd.set(name="orthoscopic",value="on")
cmd.center()
